### ISSUE TITLE
ng serve no longer has --proxy-config

### ISSUE THREAD

**Issue by mtpultz** [commercialsuicide/angular2-with-express-starter#2]
For Angular 4.x ng serve no longer has --proxy-config available - https://github.com/angular/angular-cli/wiki/serve

**Comment by commercialsuicide** [comment]
I'm using Angular 4 with proxy in my current project with no problems, seems like this addition is for the latest version of Angular 4. I'll include your addition to readme, thanks a lot for the info.

**Comment by mtpultz** [comment]
No problem.  Great repo! :)
